### ISSUE TITLE
if_else2 should by default not error if nothing to replace

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/tidyplus#26]
Otherwise going to end up with extremely fragile code plus if_else doesn't require replacement by default.

```
Error in `stopifnot()`:
ℹ In argument: `lotic = if_else2(blk == 356563941L & section == 2, FALSE, lotic)`.
ℹ In row 1.
Caused by error in `if_else2()`:
```

**Comment by aylapear** [comment]
Can you explain what behaviour your want better for this scenario? 

I thought the point of this was it was to error if no match is found to notify the person that their code is not working as intended. Do you want warnings or messages instead?

**Comment by joethorley** [comment]
Yes we want failure as opposed to warnings or messages but there should be an argument to turn erroring off and I think no error should be the default behaviour (to not break the CRAN version and because this is what most tidyverse code does)

**Comment by joethorley** [comment]
so something like
```
if_else2(x, error_if_no_change = FALSE)
```

**Comment by joethorley** [comment]
or
```
if_else2(x, error = FALSE)
```

**Comment by aylapear** [comment]
This makes sense. Thanks

**Comment by dunkenwg** [comment]
I've been having difficulties with this in my code as well and it also looks like @nehill197 has. I'll fix this up today as it's affecting alot of people
